# Generated by Django 4.2.6 on 2023-11-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_order_user_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
