# Generated by Django 4.2.6 on 2023-11-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_grand_total_order_total_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Transaction',
        ),
    ]
