# Generated by Django 4.2.6 on 2023-11-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_order_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='grand_total',
            new_name='amount_per_product',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='total_quantity',
            new_name='quantity_per_product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cart',
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
    ]
