# Generated by Django 4.2.6 on 2023-11-09 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_grand_total_transaction_amount_per_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_transaction',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
