# Generated by Django 4.2.6 on 2023-11-09 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_transaction_date_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
