# Generated by Django 4.2.6 on 2024-01-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_transaction_options_alter_transaction_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_variety',
            field=models.CharField(choices=[('Flint Corn', 'Flint Corn'), ('Sweet Corn', 'Sweet Corn'), ('Flour Corn', 'Flour Corn')], max_length=255, null=True),
        ),
    ]
