# Generated by Django 4.2.6 on 2024-01-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_item_item_variety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(choices=[('COCONUT', 'COCONUT'), ('PALAY', 'PALAY'), ('CORN', 'CORN')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_variety',
            field=models.CharField(choices=[('Fiji Dwarf', 'Fiji Dwarf'), ('Golden Malay', 'Golden Malay'), ('King Coconut', 'King Coconut'), ('West Coast Tall', 'West Coast Tall'), ('Macapuno', 'Macapuno'), ('Mestiso', 'Mestiso'), ('Matatag', 'Matatag'), ('Masipag', 'Masipag'), ('RC22', 'RC22'), ('Flint Corn', 'Flint Corn'), ('Sweet Corn', 'Sweet Corn'), ('Flour Corn', 'Flour Corn')], max_length=255, null=True),
        ),
    ]
